export const INCREMENT = 'INCREMENT';
export const DECREASE = 'DECREASE';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';

export const FETCH_EMPLOYEE_DATA = 'FETCH_EMPLOYEE_DATA';
export const FETCH_EMPLOYEE_DATA_SUCCESS = 'FETCH_EMPLOYEE_DATA_SUCCESS';

export const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS';
export const FETCH_DATA = 'FETCH_DATA';
export const SEARCHED_TEXT = 'SEARCHED_TEXT';
export const SAVE_SUGGESTIONS = 'SAVE_SUGGESTIONS';
