export const INCREMENT = 'INCREMENT';
export const DECREASE = 'DECREASE';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';

export const FETCH_EMPLOYEE_DATA = 'FETCH_EMPLOYEE_DATA';
export const FETCH_EMPLOYEE_DATA_SUCCESS = 'FETCH_EMPLOYEE_DATA_SUCCESS';
